In [1]:
import numpy as np

In [2]:
my_array= np.arange(5, 105, 5)
print(my_array)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [30]:
my_array_ten=my_array[my_array%10==0]
print(my_array_ten)

[ 10  20  30  40  50  60  70  80  90 100]


In [31]:
my_array_two_column = my_array.reshape(-1,2)
print(my_array_two_column)

[[  5  10]
 [ 15  20]
 [ 25  30]
 [ 35  40]
 [ 45  50]
 [ 55  60]
 [ 65  70]
 [ 75  80]
 [ 85  90]
 [ 95 100]]


In [32]:
my_second_array = my_array_two_column - 5
print(my_second_array)

[[ 0  5]
 [10 15]
 [20 25]
 [30 35]
 [40 45]
 [50 55]
 [60 65]
 [70 75]
 [80 85]
 [90 95]]


In [34]:
connect_array = np.hstack((my_array_two_column, my_second_array))
print(connect_array)

[[  5  10   0   5]
 [ 15  20  10  15]
 [ 25  30  20  25]
 [ 35  40  30  35]
 [ 45  50  40  45]
 [ 55  60  50  55]
 [ 65  70  60  65]
 [ 75  80  70  75]
 [ 85  90  80  85]
 [ 95 100  90  95]]


In [35]:
first_divide = connect_array[1]/connect_array[3]
second_divide = connect_array[1]/connect_array[3]
print(first_divide)
print(second_divide)

[0.42857143 0.5        0.33333333 0.42857143]
[0.42857143 0.5        0.33333333 0.42857143]


In [36]:
connect_array_2 = connect_array.copy().astype(float)
connect_array_2[1]= first_divide
connect_array_2[2]= second_divide
print(connect_array_2)

[[  5.          10.           0.           5.        ]
 [  0.42857143   0.5          0.33333333   0.42857143]
 [  0.42857143   0.5          0.33333333   0.42857143]
 [ 35.          40.          30.          35.        ]
 [ 45.          50.          40.          45.        ]
 [ 55.          60.          50.          55.        ]
 [ 65.          70.          60.          65.        ]
 [ 75.          80.          70.          75.        ]
 [ 85.          90.          80.          85.        ]
 [ 95.         100.          90.          95.        ]]


In [37]:
same_rady = np.all(connect_array_2 == connect_array, axis=1)
get_same = connect_array_2[same_rady]  
print(get_same)

[[  5.  10.   0.   5.]
 [ 35.  40.  30.  35.]
 [ 45.  50.  40.  45.]
 [ 55.  60.  50.  55.]
 [ 65.  70.  60.  65.]
 [ 75.  80.  70.  75.]
 [ 85.  90.  80.  85.]
 [ 95. 100.  90.  95.]]


In [38]:
three_lines = get_same[:3]
print(three_lines)

[[ 5. 10.  0.  5.]
 [35. 40. 30. 35.]
 [45. 50. 40. 45.]]


In [39]:
three_lines[[0,2]]=three_lines[[2,0]]
print(three_lines)

[[45. 50. 40. 45.]
 [35. 40. 30. 35.]
 [ 5. 10.  0.  5.]]


In [40]:
mean = np.mean(three_lines, axis = 1)
median = np.median(three_lines, axis = 1)
std = np.std(three_lines, axis = 1)
print(mean)
print(median)
print(std)

[45. 35.  5.]
[45. 35.  5.]
[3.53553391 3.53553391 3.53553391]


In [41]:
maximum = np.max(three_lines, axis=1 , keepdims=True)
normalisacia = tri_stroki/maximum
print(normalisacia)

[[0.9   1.    0.8   0.9  ]
 [0.875 1.    0.75  0.875]
 [0.5   1.    0.    0.5  ]]


In [14]:
import pandas as pd

In [42]:
file_path = r'C:\Users\Azama\OneDrive\Документы\Универ\Большие данные\Global Population Trends(2016-2022).csv'
bd = pd.read_csv(file_path)
print(bd)

          Country  Year Total Population Urban Population Rural Population  \
0     Afghanistan  2017                -                -                -   
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
...           ...   ...              ...              ...              ...   
1068     Zimbabwe  2017                -                -                -   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate

In [43]:
print(bd.columns)

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')


In [44]:
bd.shape

(1073, 12)

In [45]:
print(bd.columns)

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')


In [46]:
print(bd.columns)

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')


In [47]:
print(bd.head(3))

       Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  


In [48]:
bd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB


In [49]:
global_main = bd.copy()
bd = bd[bd['Total Population'] != '-']
print(bd)

          Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate

In [50]:
print(bd.describe())
print(bd.max())
print(bd.min())

              Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000
Country                    Zimbabwe
Year                           2021
Total Population             99,258
Urban Population         99,876,265
Rural Population            998,397
Population Density               99
Life Expectancy                85.0
Birth Rate                   46.127
Death Rate                     21.7
Fertility Rate                7.023
Infant Mortality Rate           9.9
Growth Rate                     5.0
dtype: object
Country                  Afghanistan
Year                            2018
Total Population           1,057,198
Urban Population                   -
Rural Population   

In [51]:
print(bd["Year"].max())
print (bd["Birth Rate"].describe())
print(bd["Total Population"].min())

2021
count    864.000000
mean      18.548384
std        9.887518
min        0.000000
25%       10.500000
50%       15.628500
75%       25.565000
max       46.127000
Name: Birth Rate, dtype: float64
1,057,198


In [52]:
sort_country = bd.sort_values(by=['Country'], ascending=[True])
print(sort_country.head())

       Country  Year Total Population Urban Population Rural Population  \
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6      Albania  2018        2,866,376        1,728,969        1,137,407   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   
6                105            79.0      10.517       8.308           1.44   

  Infant Mortality Rate Growth Rate  
1                  47.8         3.0 

In [53]:
sort = bd.sort_values(by=['Total Population'], ascending=[False])
print(sort.head())

         Country  Year Total Population Urban Population Rural Population  \
832   Seychelles  2021           99,258           57,542           41,716   
831   Seychelles  2020           98,462           56,661           41,801   
830   Seychelles  2019           97,625           55,762           41,863   
1047     Vietnam  2021       97,468,029       37,088,534       60,379,495   
829   Seychelles  2018           96,762           54,855           41,907   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
832                   -            73.0      16.800       9.300   
831                 214            77.0      15.800       6.800   
830                 212            74.0      16.400       8.100   
1047                  -            74.0      15.008       7.317   
829                 210            73.0      17.100       8.400   

     Fertility Rate Infant Mortality Rate Growth Rate  
832            2.46                  12.0         1.0  
831            2.29   

In [54]:
sort_urban  =  bd.sort_values(by=['Country','Urban Population'], ascending=[False, True])
print(sort_urban.head())

       Country  Year Total Population Urban Population Rural Population  \
1069  Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070  Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071  Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072  Zimbabwe  2021       15,993,524        5,166,388       10,827,136   
1064    Zambia  2018       17,835,893        7,762,359       10,073,534   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   
1064                 24            62.0      36.040       6.748   

     Fertility Rate Infant Mortality Rate Growth Rate  
1069          3.659                  38.0         2.0  
1070          3.599               

In [55]:
bd2 = bd.copy()
print(bd.shape)
bd2["Total Population"] = bd2["Total Population"].str.replace(',', "").astype(float)
maximum_pop = bd2["Total Population"].idxmax()
print(maximum_pop)
print('страна с наибольшей популяцией', global_main['Country'].iloc[maximum_pop])
min_pop = bd2["Total Population"].idxmin()
print(min_pop)
print('страна с наименьшей популяцией', global_main['Country'].iloc[min_pop])

(864, 12)
205
страна с наибольшей популяцией China
994
страна с наименьшей популяцией Tuvalu


In [56]:
bd.to_excel(r'C:\Users\Azama\OneDrive\Документы\Универ\Большие данные\Lab_2.xlsx', sheet_name="table")

ModuleNotFoundError: No module named 'openpyxl'